services:
  plc:
    ports:
      - 2582:3000
    build:
      context: ./repos/did-method-plc/
      dockerfile: packages/server/Dockerfile
    env_file:
      - ./.plc.env
    depends_on:
      - db

  bgs:
    ports:
      - 2470:2470
    build:
      context: ./repos/indigo/
      dockerfile: cmd/bigsky/Dockerfile
    env_file:
      - ./.bgs.env
    volumes:
      - ./data/bgs/:/data/
    depends_on:
      - db

  bsky:
    ports:
      - 2584:3000
    build:
      context: ./
      dockerfile: services/bsky/Dockerfile
    env_file:
      - ./.bsky.env
    depends_on:
      - db
      - redis

  bsky-daemon:
    build:
      context: ./
      dockerfile: services/bsky/Dockerfile
    command: node --enable-source-maps daemon.js
    env_file:
      - ./.bsky.env
    depends_on:
      - bsky
      - db
      - redis

  bsky-indexer:
    build:
      context: ./
      dockerfile: services/bsky/Dockerfile
    command: node --enable-source-maps indexer.js
    env_file:
      - ./.bsky.env
    volumes:
      - ./data/bsky/cache/:/cache/
    depends_on:
      - bsky
      - db
      - redis

  bsky-ingester:
    build:
      context: ./
      dockerfile: services/bsky/Dockerfile
    command: node --enable-source-maps ingester.js
    env_file:
      - ./.bsky.env
    volumes:
      - ./data/bsky/cache/:/cache/
    depends_on:
      - bsky
      - db
      - redis

  mod:
    ports:
      - 2585:3000
    build:
      context: ./
      dockerfile: services/ozone/Dockerfile
    env_file:
      - ./.mod.env
    depends_on:
      - db

  mod-daemon:
    build:
      context: ./
      dockerfile: services/ozone/Dockerfile
    command: node --enable-source-maps daemon.js
    env_file:
      - ./.mod.env
    depends_on:
      - mod
      - db

  pds:
    ports:
      - 2583:3000
    build:
      context: ./
      dockerfile: services/pds/Dockerfile
    env_file:
      - ./.pds.env
    volumes:
      - ./data/pds/:/data/
    depends_on:
      - db

  social-app:
    ports:
      - 8100:8100
    build:
      context: ./repos/social-app/
      dockerfile: Dockerfile
    env_file:
      - ./.web.env
    command: "/usr/bin/bskyweb serve"

  db:
    image: postgres:latest
    env_file:
      - ./.db.env
    volumes:
      - ./postgres/init/:/docker-entrypoint-initdb.d/
      - ./data/db/:/var/lib/postgresql/data/

  redis:
    image: redis
    volumes:
      - ./data/redis/:/data/
#  feed-generator:
 #   ports:
  #    - 2586:3000
  #  build:
   #   context: ./repos/feed-generator/
    #restart: always
    #env_file:
    #  - ./.feed.env
    #volumes:
    #  - ./data/feed-generator/:/data/
